### ISSUE TITLE
ImportError: bad magic number in 'skillshare

### ISSUE THREAD

**Issue by rallabandisrinivas** [Cassiedee/Skillshare-Premium-Downloader#1]
$ python dl.py https://www.skillshare.com/classes/Grafana/1350262926
Traceback (most recent call last):
  File "dl.py", line 2, in <module>
    from skillshare import Skillshare
ImportError: bad magic number in 'skillshare': b'B\r\r\n'

**Comment by alternistom** [comment]
Same for me, can't use it

**Comment by Cassiedee** [comment]
The dl.py file needs to be worked on. Its dependencies need to be updated along with the downloader script. I'll be working on it soon.
