### ISSUE TITLE
Seems they patched access, 403 forbidden

### ISSUE THREAD

**Issue by the-matrixitian** [Cassiedee/Skillshare-Premium-Downloader#2]
Executing the download throws a 403 error in the console, so it seems they have patched it :P Still thanks for making it public

**Comment by Cassiedee** [comment]
Yeah that is unfortunately true....Source will still be made public tho just in case anyone needs it for research or practicing reverse engineering. I made this for a university assignment a long time ago and forgot about it lmao. Thanks for letting me know!
